### ISSUE TITLE
'prerender-node' dependency missing in package.json of vscode extension

### ISSUE THREAD

**Issue by maheshoz** [harryheman/Modern-HTML-Starter-Template#7]
I tried the vscode extension to generate the template and run npm install. had error, found that the 'prerender-node' is not added to the dependencies.

![image](https://user-images.githubusercontent.com/35638589/102270316-dbec7e80-3f43-11eb-8837-15973a0d0c8a.png)

i think the vscode extension needs to be updated.

**Comment by harryheman** [comment]
Thank you, my friend
